### ISSUE TITLE
Category hints doesnt work

### ISSUE THREAD

**Issue by CodingLama** [exander77/vicuna#1]
Priority 2

Category hints worked like hints on Wikimedia Commons, looking for the same string as when typing. Now they don't work. Way to reproduce:

1. Add photo
2. In the "categories" field writhe whatever string, e.g "Lipová"
3. A dialog box appears below with the text "Loading...."Lipová"" and immediately it is replaced by a text "No categories". But we know that there is a category which has _Lipová_ in the string, e.g.: https://commons.wikimedia.org/wiki/Category:Lipov%C3%A1_alej_(P%C3%ADsek)

**Comment by michal-josef-spacek** [comment]
Was fixed in https://github.com/yarl/vicuna/pull/172/commits/835c161d96959ea82acec4936dcc64550afb234c

**Comment by CodingLama** [comment]
> Was fixed in [yarl@835c161](https://github.com/yarl/vicuna/commit/835c161d96959ea82acec4936dcc64550afb234c)

OK, thx.

**Comment by exander77** [comment]
I backported this.
