### ISSUE TITLE
Link from Wikimedia Commons to download doesn't work

### ISSUE THREAD

**Issue by CodingLama** [exander77/vicuna#10]
All systems, Priority 1

The link from Wikimedia Commons' VicunaUploader main [page](https://commons.wikimedia.org/wiki/Commons:Vicu%C3%B1aUploader) does not lead to the page, where the latest version could be downloaded. Here I would propose if possible to provide one page, where published versions are stored and we just move the actually tested version on the top, that we don't need to manipulate the Commons' page.

**Comment by CodingLama** [comment]
Now I see, the problem is on Wikimedia Commons, that [someone has changed](https://commons.wikimedia.org/w/index.php?title=Commons:Vicu%C3%B1aUploader&diff=prev&oldid=616872746) the page to a defunct URL. So I guess, this issue could be closed.

**Comment by exander77** [comment]
Btw, the current version is always here: https://commons.wikimedia.org/wiki/User:Exander77/VicunaUploader/version
This is the version that is used for update checks.

**Comment by CodingLama** [comment]
> Btw, the current version is always here: https://commons.wikimedia.org/wiki/User:Exander77/VicunaUploader/version This is the version that is used for update checks.

I see. [I have removed](https://commons.wikimedia.org/w/index.php?title=Commons%3AVicu%C3%B1aUploader&type=revision&diff=623415559&oldid=622885847) version info from the main page and I am not sure if we need to inform on the main page what is the latest version. I would inform you about major releases on the talk page.

**Comment by CodingLama** [comment]
OK, finally I have decided to subst it to the VU main page. It might be useful for the users to see, what is the actual version.
