### ISSUE TITLE
Cannot start VU

### ISSUE THREAD

**Issue by CodingLama** [exander77/vicuna#17]
I have downloaded 1.3.3a and openJDK 17 running on Ubuntu 20.04.4 LTS. I double click on 1.3.3a in bin dirrectory. Pop up window comes, I click on Run in terminall. The terminal comes up and inmediatelly switch off. No windows of VU.

**Comment by exander77** [comment]
@CodingLama Open a cmd and start application from within cmd, there is definitely some error message, but the terminal window closes so fast that you are unable to see it. If you start it from within cmd Terminal, you will be able to see what is going on.

**Comment by CodingLama** [comment]
So, I have fixed the Java locally and it works.
