### ISSUE TITLE
Change link to the new version

### ISSUE THREAD

**Issue by CodingLama** [exander77/vicuna#4]
Priority: 2, all operation systems

Before VU starts it offers a pop-up window, about the new version. In this case 1.25. If a person clicks on Download it is directed to yarl's website to download 1.23. I think VU should check whether there is a new version in the exander77 repository and if so provide its installation or download.

**Comment by exander77** [comment]
New version page: https://commons.wikimedia.org/wiki/User:Exander77/VicunaUploader/version
