### ISSUE TITLE
Upload not successful, reason unknown

### ISSUE THREAD

**Issue by CodingLama** [exander77/vicuna#6]
Priority 1, Win, Linux

Users report some files are left **not uploaded** after they have committed the upload. Sometimes it is the case of all files in the bunch. We cannot determine the cause due to #5, but it might be related to the reasons mentioned in #3. Due to the fact it may happen with a whole bunch of files, it's blocking.

**Comment by exander77** [comment]
Since v1.3.1a logging of failed upload goes to console.
